# Generated by Django 5.2 on 2025-04-19 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='reservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(default='')),
                ('uduario', models.TextField(default='')),
                ('hotel', models.TextField(default='')),
                ('plan', models.TextField(default='')),
                ('tip_hab', models.TextField(default='')),
                ('tip_vista', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(0, 'Admin'), (1, 'Cliente')], default=1)),
                ('emails_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.notification')),
                ('reservacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reservaciones')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
