# Generated by Django 5.0 on 2025-04-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reservaciones_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaciones',
            name='cuentas_pesonas',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reservaciones',
            name='desde',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservaciones',
            name='fecha_de_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservaciones',
            name='hasta',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservaciones',
            name='usuario_on',
            field=models.BooleanField(default=True),
        ),
    ]
