# Generated by Django 5.0 on 2025-04-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reservaciones_cuentas_pesonas_reservaciones_desde_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hoteles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField(default='')),
                ('price', models.TextField(default='')),
                ('img', models.TextField(default='')),
            ],
        ),
    ]
