# Generated by Django 5.0 on 2025-04-23 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hoteles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='reservacion',
        ),
        migrations.AddField(
            model_name='reservaciones',
            name='usuario_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to='api.usuario'),
        ),
    ]
