# Generated by Django 5.0 on 2025-04-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_reservaciones_desde_alter_reservaciones_hasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaciones',
            name='desde',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='hasta',
            field=models.TextField(default=''),
        ),
    ]
