# Generated by Django 5.0 on 2025-04-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_reservaciones_desde_alter_reservaciones_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaciones',
            name='price',
            field=models.TextField(default=''),
        ),
    ]
