# Generated by Django 5.0 on 2025-04-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reservaciones_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaciones',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
